# Generated by Django 2.2.10 on 2020-06-10 00:05

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=100)),
                ('album_logo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='名字')),
                ('author', models.CharField(max_length=128, verbose_name='作者')),
                ('audio_file', models.URLField()),
                ('content', models.TextField(verbose_name='音频内容')),
                ('created', models.DateTimeField(auto_now=True)),
                ('size', models.FloatField(verbose_name='文件大小')),
                ('view_num', models.IntegerField(default=0, verbose_name='播放数')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album', verbose_name='音频专辑')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=32, verbose_name='单词内容')),
            ],
        ),
        migrations.CreateModel(
            name='UserSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.SmallIntegerField(verbose_name='当前状态')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song', verbose_name='歌曲')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.User', verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='word',
            field=models.ManyToManyField(to='music.Word', verbose_name='单词'),
        ),
    ]
