# Generated by Django 2.2.10 on 2020-06-11 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='translation',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='翻译内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(default='英语', max_length=100),
        ),
    ]
