# Generated by Django 2.2.10 on 2020-06-26 12:27

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCode',
            fields=[
                ('code', models.CharField(default=music.models.gen_newcode, max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
