# Generated by Django 2.2.10 on 2020-06-28 13:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_registercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='created',
            field=music.models.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='album',
            name='modified',
            field=music.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='registercode',
            name='created',
            field=music.models.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='registercode',
            name='modified',
            field=music.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='song',
            name='modified',
            field=music.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=music.models.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='user',
            name='modified',
            field=music.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='usersong',
            name='created',
            field=music.models.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='usersong',
            name='modified',
            field=music.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='word',
            name='created',
            field=music.models.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='word',
            name='modified',
            field=music.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', music.models.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', music.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.User', verbose_name='用户')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Word', verbose_name='单词')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
