# Generated by Django 2.2.10 on 2020-06-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_messageboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboard',
            name='title',
            field=models.CharField(default='公告', max_length=32, verbose_name='公告标题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messageboard',
            name='content',
            field=models.TextField(verbose_name='公告内容'),
        ),
    ]
